/**
 * `mcp completions` — generate shell completion scripts.
 *
 * Two modes:
 * 1. Script generation: `mcp completions bash|zsh|fish` → outputs installable script
 * 2. Dynamic helpers: `mcp completions --servers|--tools <server>|--aliases` → one name per line
 */

import type { AliasInfo, ServerStatus, ToolInfo } from "@mcp-cli/core";
import { ipcCall as realIpcCall, isDaemonRunning as realIsDaemonRunning } from "@mcp-cli/core";
import { printError } from "../output";

export interface CompletionDeps {
  ipcCall: typeof realIpcCall;
  isDaemonRunning: typeof realIsDaemonRunning;
}

const defaultDeps: CompletionDeps = { ipcCall: realIpcCall, isDaemonRunning: realIsDaemonRunning };

/** Top-level subcommands for the mcp CLI */
export const SUBCOMMANDS = [
  "ls",
  "call",
  "info",
  "grep",
  "status",
  "config",
  "add",
  "add-json",
  "remove",
  "get",
  "auth",
  "alias",
  "run",
  "logs",
  "typegen",
  "restart",
  "shutdown",
  "tools",
  "search",
  "install",
  "registry",
  "completions",
  "help",
] as const;

/** Subcommands for `mcp alias` */
export const ALIAS_SUBCOMMANDS = ["ls", "save", "show", "edit", "rm"] as const;

/** Subcommands for `mcp config` */
export const CONFIG_SUBCOMMANDS = ["show", "sources", "set", "get"] as const;

/** Subcommands that accept a server name as their first argument */
const SERVER_COMMANDS = ["call", "info", "ls", "tools", "auth", "logs", "restart", "remove", "get"];

/** Subcommands that accept a tool name as their second argument (after server) */
const TOOL_COMMANDS = ["call", "info"];

/** Alias subcommands that accept an alias name */
const ALIAS_NAME_COMMANDS = ["show", "edit", "rm"];

export async function cmdCompletions(args: string[], deps?: CompletionDeps): Promise<void> {
  const d = deps ?? defaultDeps;
  // Dynamic data helpers (called by the generated scripts)
  if (args[0] === "--servers") {
    await printServers(d);
    return;
  }
  if (args[0] === "--tools" && args[1]) {
    await printTools(args[1], d);
    return;
  }
  if (args[0] === "--aliases") {
    await printAliases(d);
    return;
  }

  // Script generation
  const shell = args[0];
  switch (shell) {
    case "bash":
      console.log(bashScript());
      return;
    case "zsh":
      console.log(zshScript());
      return;
    case "fish":
      console.log(fishScript());
      return;
    default:
      printError("Usage: mcp completions {bash|zsh|fish}");
      printError("");
      printError("Installation:");
      printError('  eval "$(mcp completions bash)"   # add to ~/.bashrc');
      printError('  eval "$(mcp completions zsh)"    # add to ~/.zshrc');
      printError("  mcp completions fish > ~/.config/fish/completions/mcp.fish");
      process.exit(1);
  }
}

/** Print server names, one per line. Skips if daemon not running. */
async function printServers(deps: CompletionDeps): Promise<void> {
  try {
    if (!(await deps.isDaemonRunning())) return;
    const servers = (await deps.ipcCall("listServers")) as ServerStatus[];
    for (const s of servers) {
      console.log(s.name);
    }
  } catch {
    // Daemon not running — output nothing
  }
}

/** Print tool names for a server, one per line. Skips if daemon not running. */
async function printTools(server: string, deps: CompletionDeps): Promise<void> {
  try {
    if (!(await deps.isDaemonRunning())) return;
    const tools = (await deps.ipcCall("listTools", { server })) as ToolInfo[];
    for (const t of tools) {
      console.log(t.name);
    }
  } catch {
    // Daemon not running — output nothing
  }
}

/** Print alias names, one per line. Skips if daemon not running. */
async function printAliases(deps: CompletionDeps): Promise<void> {
  try {
    if (!(await deps.isDaemonRunning())) return;
    const aliases = (await deps.ipcCall("listAliases")) as AliasInfo[];
    for (const a of aliases) {
      console.log(a.name);
    }
  } catch {
    // Daemon not running — output nothing
  }
}

// -- Shell script generators --

export function bashScript(): string {
  return `# mcp bash completion — generated by "mcp completions bash"
# Add to ~/.bashrc: eval "$(mcp completions bash)"

_mcp_completions() {
  local cur prev words cword
  _init_completion || return

  local subcommands="${SUBCOMMANDS.join(" ")}"
  local alias_subcommands="${ALIAS_SUBCOMMANDS.join(" ")}"
  local config_subcommands="${CONFIG_SUBCOMMANDS.join(" ")}"
  local server_commands="${SERVER_COMMANDS.join(" ")}"
  local tool_commands="${TOOL_COMMANDS.join(" ")}"
  local alias_name_commands="${ALIAS_NAME_COMMANDS.join(" ")}"

  # mcp <TAB> — complete subcommands
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
    return
  fi

  local cmd="\${words[1]}"

  # mcp completions <TAB>
  if [[ "$cmd" == "completions" && $cword -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
    return
  fi

  # mcp config <TAB>
  if [[ "$cmd" == "config" && $cword -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "$config_subcommands" -- "$cur") )
    return
  fi

  # mcp alias <TAB> — alias subcommands
  if [[ "$cmd" == "alias" && $cword -eq 2 ]]; then
    COMPREPLY=( $(compgen -W "$alias_subcommands" -- "$cur") )
    return
  fi

  # mcp alias show|edit|rm <TAB> — alias names
  if [[ "$cmd" == "alias" && $cword -eq 3 ]]; then
    local alias_sub="\${words[2]}"
    for ac in $alias_name_commands; do
      if [[ "$alias_sub" == "$ac" ]]; then
        local aliases
        aliases="$(mcp completions --aliases 2>/dev/null)"
        COMPREPLY=( $(compgen -W "$aliases" -- "$cur") )
        return
      fi
    done
    return
  fi

  # mcp run <TAB> — alias names
  if [[ "$cmd" == "run" && $cword -eq 2 ]]; then
    local aliases
    aliases="$(mcp completions --aliases 2>/dev/null)"
    COMPREPLY=( $(compgen -W "$aliases" -- "$cur") )
    return
  fi

  # mcp <server-command> <TAB> — server names
  if [[ $cword -eq 2 ]]; then
    for sc in $server_commands; do
      if [[ "$cmd" == "$sc" ]]; then
        local servers
        servers="$(mcp completions --servers 2>/dev/null)"
        COMPREPLY=( $(compgen -W "$servers" -- "$cur") )
        return
      fi
    done
    return
  fi

  # mcp call|info <server> <TAB> — tool names
  if [[ $cword -eq 3 ]]; then
    for tc in $tool_commands; do
      if [[ "$cmd" == "$tc" ]]; then
        local tools
        tools="$(mcp completions --tools "\${words[2]}" 2>/dev/null)"
        COMPREPLY=( $(compgen -W "$tools" -- "$cur") )
        return
      fi
    done
    return
  fi
}

complete -F _mcp_completions mcp`;
}

export function zshScript(): string {
  return `#compdef mcp
# mcp zsh completion — generated by "mcp completions zsh"
# Add to ~/.zshrc: eval "$(mcp completions zsh)"

_mcp() {
  local -a subcommands
  subcommands=(${SUBCOMMANDS.map((s) => `'${s}'`).join(" ")})

  local -a alias_subcommands
  alias_subcommands=(${ALIAS_SUBCOMMANDS.map((s) => `'${s}'`).join(" ")})

  local -a config_subcommands
  config_subcommands=(${CONFIG_SUBCOMMANDS.map((s) => `'${s}'`).join(" ")})

  local -a server_commands
  server_commands=(${SERVER_COMMANDS.map((s) => `'${s}'`).join(" ")})

  local -a tool_commands
  tool_commands=(${TOOL_COMMANDS.map((s) => `'${s}'`).join(" ")})

  local -a alias_name_commands
  alias_name_commands=(${ALIAS_NAME_COMMANDS.map((s) => `'${s}'`).join(" ")})

  # mcp <TAB>
  if (( CURRENT == 2 )); then
    _describe 'command' subcommands
    return
  fi

  local cmd=\${words[2]}

  # mcp completions <TAB>
  if [[ "$cmd" == "completions" ]] && (( CURRENT == 3 )); then
    local -a shells
    shells=('bash' 'zsh' 'fish')
    _describe 'shell' shells
    return
  fi

  # mcp config <TAB>
  if [[ "$cmd" == "config" ]] && (( CURRENT == 3 )); then
    _describe 'config subcommand' config_subcommands
    return
  fi

  # mcp alias <TAB>
  if [[ "$cmd" == "alias" ]] && (( CURRENT == 3 )); then
    _describe 'alias subcommand' alias_subcommands
    return
  fi

  # mcp alias show|edit|rm <TAB>
  if [[ "$cmd" == "alias" ]] && (( CURRENT == 4 )); then
    local alias_sub=\${words[3]}
    if (( \${alias_name_commands[(Ie)$alias_sub]} )); then
      local -a aliases
      aliases=(\${(f)"$(mcp completions --aliases 2>/dev/null)"})
      _describe 'alias' aliases
      return
    fi
    return
  fi

  # mcp run <TAB>
  if [[ "$cmd" == "run" ]] && (( CURRENT == 3 )); then
    local -a aliases
    aliases=(\${(f)"$(mcp completions --aliases 2>/dev/null)"})
    _describe 'alias' aliases
    return
  fi

  # mcp <server-command> <TAB> — server names
  if (( CURRENT == 3 )) && (( \${server_commands[(Ie)$cmd]} )); then
    local -a servers
    servers=(\${(f)"$(mcp completions --servers 2>/dev/null)"})
    _describe 'server' servers
    return
  fi

  # mcp call|info <server> <TAB> — tool names
  if (( CURRENT == 4 )) && (( \${tool_commands[(Ie)$cmd]} )); then
    local -a tools
    tools=(\${(f)"$(mcp completions --tools \${words[3]} 2>/dev/null)"})
    _describe 'tool' tools
    return
  fi
}

_mcp "$@"`;
}

export function fishScript(): string {
  return `# mcp fish completion — generated by "mcp completions fish"
# Save to: ~/.config/fish/completions/mcp.fish

# Disable file completions by default
complete -c mcp -f

# Helper: current number of non-option tokens on the commandline
function __mcp_token_count
  set -l tokens (commandline -opc)
  count $tokens
end

# Helper: get the nth token (1-indexed, token 1 is "mcp")
function __mcp_token
  set -l tokens (commandline -opc)
  if test (count $tokens) -ge $argv[1]
    echo $tokens[$argv[1]]
  end
end

# Subcommands — only when no subcommand given yet
complete -c mcp -n '__mcp_token_count -eq 1' -a '${SUBCOMMANDS.join(" ")}' -d 'mcp subcommand'

# mcp completions <TAB>
complete -c mcp -n '__mcp_token_count -eq 2; and __mcp_token 2 = completions' -a 'bash zsh fish' -d 'shell'

# mcp config <TAB>
complete -c mcp -n '__mcp_token_count -eq 2; and __mcp_token 2 = config' -a '${CONFIG_SUBCOMMANDS.join(" ")}' -d 'config subcommand'

# mcp alias <TAB> — alias subcommands
complete -c mcp -n '__mcp_token_count -eq 2; and __mcp_token 2 = alias' -a '${ALIAS_SUBCOMMANDS.join(" ")}' -d 'alias subcommand'

# mcp alias show|edit|rm <TAB> — alias names
${ALIAS_NAME_COMMANDS.map(
  (cmd) =>
    `complete -c mcp -n '__mcp_token_count -eq 3; and __mcp_token 2 = alias; and __mcp_token 3 = ${cmd}' -a '(mcp completions --aliases 2>/dev/null)' -d 'alias'`,
).join("\n")}

# mcp run <TAB> — alias names
complete -c mcp -n '__mcp_token_count -eq 2; and __mcp_token 2 = run' -a '(mcp completions --aliases 2>/dev/null)' -d 'alias'

# Server name completion for: ${SERVER_COMMANDS.join(", ")}
${SERVER_COMMANDS.map(
  (cmd) =>
    `complete -c mcp -n '__mcp_token_count -eq 2; and __mcp_token 2 = ${cmd}' -a '(mcp completions --servers 2>/dev/null)' -d 'server'`,
).join("\n")}

# Tool name completion for: ${TOOL_COMMANDS.join(", ")}
${TOOL_COMMANDS.map(
  (cmd) =>
    `complete -c mcp -n '__mcp_token_count -eq 3; and __mcp_token 2 = ${cmd}' -a '(mcp completions --tools (__mcp_token 3) 2>/dev/null)' -d 'tool'`,
).join("\n")}`;
}
