/**
 * mcx typegen — generate TypeScript declarations from cached tool schemas.
 *
 * Writes ~/.mcp-cli/mcp-cli.d.ts so alias scripts get editor autocomplete
 * when importing from "mcp-cli".
 */

import { writeFileSync } from "node:fs";
import { type JsonSchema, type ToolInfo, ipcCall, jsonSchemaToTs, options } from "@mcp-cli/core";
import { printError } from "../output";

/** Higher limits than default for declaration files — we want full detail. */
const SCHEMA_OPTS = { maxDepth: 4, maxProps: 20 };

export async function cmdTypegen(_args: string[]): Promise<void> {
  const tools = await ipcCall("listTools");

  if (tools.length === 0) {
    printError("No tools in cache. Run 'mcx ls <server>' first to populate the cache.");
    return;
  }

  const dts = generateDeclarations(tools);
  writeFileSync(options.TYPES_PATH, dts, "utf-8");
  console.error(`Wrote ${options.TYPES_PATH} (${tools.length} tools)`);
}

/**
 * Generate a `declare module "mcp-cli"` block from a list of tools.
 * Pure function — exported for testing.
 */
export function generateDeclarations(tools: ToolInfo[]): string {
  const grouped = groupByServer(tools);
  const serverNames = Object.keys(grouped).sort();

  const serverBlocks = serverNames.map((server) => {
    const serverTools = grouped[server].sort((a, b) => a.name.localeCompare(b.name));
    const methods = serverTools.map((t) => formatMethod(t, "      "));
    return `    ${ident(server)}: {\n${methods.join("\n")}\n    };`;
  });

  const lines = [
    "// Auto-generated by `mcx typegen` — do not edit",
    `declare module "mcp-cli" {`,
    "  interface Mcp {",
    serverBlocks.join("\n"),
    "  }",
    "  export const mcp: Mcp;",
    "  export const args: Record<string, string>;",
    "  export function file(path: string): Promise<string>;",
    "  export function json(path: string): Promise<unknown>;",
    "  export function parsePythonRepr(raw: unknown): unknown;",
    "",
    "  // -- defineAlias API --",
    "  interface AliasContext {",
    "    mcp: Mcp;",
    "    args: Record<string, string>;",
    "    file: (path: string) => Promise<string>;",
    "    json: (path: string) => Promise<unknown>;",
    "  }",
    "  interface AliasDefinition<I = unknown, O = unknown> {",
    "    name: string;",
    "    description: string;",
    "    input: import('zod').ZodType<I>;",
    "    output: import('zod').ZodType<O>;",
    "    fn: (input: I, ctx: AliasContext) => O | Promise<O>;",
    "  }",
    "  export function defineAlias<I, O>(defOrFactory:",
    "    | AliasDefinition<I, O>",
    "    | ((ctx: { mcp: Mcp; z: typeof import('zod') }) => AliasDefinition<I, O>)",
    "  ): void;",
    "  export const z: typeof import('zod');",
    "}",
    "", // trailing newline
  ];

  return lines.join("\n");
}

// -- Internals --

function groupByServer(tools: ToolInfo[]): Record<string, ToolInfo[]> {
  const map: Record<string, ToolInfo[]> = {};
  for (const t of tools) {
    if (!map[t.server]) map[t.server] = [];
    map[t.server].push(t);
  }
  return map;
}

function formatMethod(tool: ToolInfo, indent: string): string {
  const schema = tool.inputSchema as JsonSchema;
  const hasParams = schema.properties && Object.keys(schema.properties).length > 0;
  const argsType = hasParams ? jsonSchemaToTs(schema, SCHEMA_OPTS) : "";
  const sig = hasParams ? `(args: ${argsType})` : "()";
  const lines: string[] = [];

  if (tool.description) {
    lines.push(`${indent}/** ${escapeComment(tool.description)} */`);
  }
  lines.push(`${indent}${ident(tool.name)}${sig}: Promise<unknown>;`);
  return lines.join("\n");
}

/** Ensure a name is a valid JS identifier; quote it if not. */
function ident(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `"${name}"`;
}

/** Escape closing sequences inside JSDoc comments. */
function escapeComment(text: string): string {
  return text.replace(/\*\//g, "*\\/").replace(/\n/g, " ");
}
