import { describe, expect, test } from "bun:test";
import type { ToolInfo } from "@mcp-cli/core";
import { generateDeclarations } from "./typegen";

function tool(server: string, name: string, schema: Record<string, unknown>, desc = ""): ToolInfo {
  return { server, name, description: desc, inputSchema: schema };
}

describe("generateDeclarations", () => {
  test("single tool with required and optional params", () => {
    const tools = [
      tool(
        "atlas",
        "search",
        {
          type: "object",
          properties: { query: { type: "string" }, limit: { type: "number" } },
          required: ["query"],
        },
        "Search content",
      ),
    ];
    const dts = generateDeclarations(tools);
    expect(dts).toContain('declare module "mcp-cli"');
    expect(dts).toContain("/** Search content */");
    expect(dts).toContain("search(args: {query: string, limit?: number}): Promise<unknown>;");
    expect(dts).toContain("atlas: {");
  });

  test("tool with no params", () => {
    const tools = [tool("svc", "ping", {})];
    const dts = generateDeclarations(tools);
    expect(dts).toContain("ping(): Promise<unknown>;");
  });

  test("tool with empty properties object", () => {
    const tools = [tool("svc", "ping", { type: "object", properties: {} })];
    const dts = generateDeclarations(tools);
    expect(dts).toContain("ping(): Promise<unknown>;");
  });

  test("multiple servers are sorted", () => {
    const tools = [tool("zeta", "a", {}), tool("alpha", "b", {})];
    const dts = generateDeclarations(tools);
    const alphaIdx = dts.indexOf("alpha:");
    const zetaIdx = dts.indexOf("zeta:");
    expect(alphaIdx).toBeLessThan(zetaIdx);
  });

  test("tools within a server are sorted", () => {
    const tools = [tool("svc", "zebra", {}), tool("svc", "apple", {})];
    const dts = generateDeclarations(tools);
    const appleIdx = dts.indexOf("apple()");
    const zebraIdx = dts.indexOf("zebra()");
    expect(appleIdx).toBeLessThan(zebraIdx);
  });

  test("description becomes JSDoc comment", () => {
    const tools = [tool("s", "t", {}, "Does something useful")];
    const dts = generateDeclarations(tools);
    expect(dts).toContain("/** Does something useful */");
  });

  test("no description omits JSDoc", () => {
    const tools = [tool("s", "t", {})];
    const dts = generateDeclarations(tools);
    expect(dts).not.toContain("/**");
  });

  test("enum params", () => {
    const tools = [
      tool("svc", "export", {
        type: "object",
        properties: { format: { enum: ["json", "xml"] } },
        required: ["format"],
      }),
    ];
    const dts = generateDeclarations(tools);
    expect(dts).toContain("format: 'json' | 'xml'");
  });

  test("exports mcp, args, file, json", () => {
    const dts = generateDeclarations([tool("s", "t", {})]);
    expect(dts).toContain("export const mcp: Mcp;");
    expect(dts).toContain("export const args: Record<string, string>;");
    expect(dts).toContain("export function file(path: string): Promise<string>;");
    expect(dts).toContain("export function json(path: string): Promise<unknown>;");
  });

  test("server name requiring quoting", () => {
    const tools = [tool("my-server", "call", {})];
    const dts = generateDeclarations(tools);
    expect(dts).toContain('"my-server": {');
  });

  test("tool name requiring quoting", () => {
    const tools = [tool("s", "get-page", {})];
    const dts = generateDeclarations(tools);
    expect(dts).toContain('"get-page"(): Promise<unknown>;');
  });

  test("description with */ is escaped", () => {
    const tools = [tool("s", "t", {}, "Does */ things")];
    const dts = generateDeclarations(tools);
    expect(dts).toContain("/** Does *\\/ things */");
    expect(dts).not.toMatch(/\/\*\*.*\*\/.*\*\//m); // no premature close
  });

  test("auto-generated header comment", () => {
    const dts = generateDeclarations([tool("s", "t", {})]);
    expect(dts).toStartWith("// Auto-generated by `mcp typegen`");
  });

  test("trailing newline", () => {
    const dts = generateDeclarations([tool("s", "t", {})]);
    expect(dts).toEndWith("\n");
  });
});
