#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { $ } from "bun";

const TARGETS = ["bun-darwin-arm64", "bun-darwin-x64", "bun-linux-x64", "bun-linux-arm64"] as const;

const args = process.argv.slice(2);
const releaseMode = args.includes("--release");
const targetArg = args.find((a) => a.startsWith("--target="))?.split("=")[1];

// ── Embed jq-web WASM into generated TypeScript ──
console.log("Embedding jq-web WASM...");
const jqWebDir = resolve("node_modules/jq-web");
const wasmBytes = readFileSync(resolve(jqWebDir, "jq.wasm"));
const jsBytes = readFileSync(resolve(jqWebDir, "jq.js"));

const wasmCompressed = Bun.zstdCompressSync(new Uint8Array(wasmBytes));
const wasmZstdBase64 = Buffer.from(wasmCompressed).toString("base64");
const jsBase64 = Buffer.from(jsBytes).toString("base64");

const embeddedPath = resolve("packages/command/src/jq/jq-web-embedded.ts");
writeFileSync(
  embeddedPath,
  `// AUTO-GENERATED by scripts/build.ts — do not edit\nexport const JQ_WASM_ZSTD_BASE64 = "${wasmZstdBase64}";\nexport const JQ_JS_BASE64 = "${jsBase64}";\n`,
);
console.log(
  `  WASM: ${(wasmBytes.length / 1024).toFixed(0)}KB → zstd ${(wasmCompressed.length / 1024).toFixed(0)}KB → base64 ${(wasmZstdBase64.length / 1024).toFixed(0)}KB`,
);
console.log(`  JS: ${(jsBytes.length / 1024).toFixed(0)}KB → base64 ${(jsBase64.length / 1024).toFixed(0)}KB`);

await $`mkdir -p dist`;

if (releaseMode) {
  const targets = targetArg ? TARGETS.filter((t) => t === targetArg) : [...TARGETS];

  if (targetArg && targets.length === 0) {
    console.error(`Unknown target: ${targetArg}`);
    console.error(`Valid targets: ${TARGETS.join(", ")}`);
    process.exit(1);
  }

  for (const target of targets) {
    const suffix = target.replace("bun-", "");
    console.log(`Building for ${suffix}...`);
    await Promise.all([
      $`bun build --compile --minify --target=${target} packages/daemon/src/index.ts --outfile dist/mcpd-${suffix}`,
      $`bun build --compile --minify --target=${target} packages/command/src/index.ts --outfile dist/mcp-${suffix}`,
      $`bun build --compile --minify --target=${target} --external react-devtools-core packages/control/src/index.tsx --outfile dist/mcpctl-${suffix}`,
    ]);
  }

  console.log("Release build complete.");
} else {
  // Dev build: current platform, simple names
  await Promise.all([
    $`bun build --compile --minify packages/daemon/src/index.ts --outfile dist/mcpd`,
    $`bun build --compile --minify packages/command/src/index.ts --outfile dist/mcp`,
    $`bun build --compile --minify --external react-devtools-core packages/control/src/index.tsx --outfile dist/mcpctl`,
  ]);
  console.log("Built: dist/mcpd, dist/mcp, dist/mcpctl");
}
